// Code generated by mockery v1.0.0. DO NOT EDIT.
package main

import mock "github.com/stretchr/testify/mock"

// mockHandsStringParser is an autogenerated mock type for the handsStringParser type
type mockHandsStringParser struct {
	mock.Mock
}

// parseHands provides a mock function with given fields: _a0
func (_m *mockHandsStringParser) parseHands(_a0 string) (Hand, Hand, error) {
	ret := _m.Called(_a0)

	var r0 Hand
	if rf, ok := ret.Get(0).(func(string) Hand); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Hand)
		}
	}

	var r1 Hand
	if rf, ok := ret.Get(1).(func(string) Hand); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(Hand)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
