// Code generated by mockery v1.0.0. DO NOT EDIT.
package main

import mock "github.com/stretchr/testify/mock"

// mockComparator is an autogenerated mock type for the comparator type
type mockComparator struct {
	mock.Mock
}

// IsFirstPlayerWinner provides a mock function with given fields: hands
func (_m *mockComparator) IsFirstPlayerWinner(hands string) (bool, error) {
	ret := _m.Called(hands)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(hands)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hands)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
